[workspace]
members = [
	"crates/dynamic-music",
	"crates/ghost-noise",
	"crates/metronome",
	"crates/score-counter",
	"crates/seamless-loop-with-intro",
	"crates/simple-sound-playback",
]

[profile.dev.package."*"]
opt-level = 3
